#ifndef SOILFRAMEWORK_H
#define SOILFRAMEWORK_H

#include "hash_functions.h"
#include "load_save_files.h"
#include "pixmap_functions.h"
#include "sdl_functions.h"
#include "soilbutton.h"
#include "soilcontrol.h"
#include "soilcrypt.h"
#include "soildropmenu.h"
#include "soilenginecontrol.h"
#include "soilengine.h"
#include "soilfont.h"
#include "soilimage.h"
#include "soilincstring.h"
#include "soilinfrastring.h"
#include "soilinput.h"
#include "soillabel.h"
#include "soillayout.h"
#include "soilstringlist.h"
#include "soillistwidget.h"
#include "soilmembound.h"
#include "soilobject.h"
#include "soilpixmap.h"
#include "soilprogressbar.h"
#include "soilpxmembound.h"
#include "soilslider.h"
#include "soilstring.h"
#include "soiltext.h"
#include "soiltextblock.h"
#include "soiltextfield.h"
#include "soiltextrecord.h"
#include "soiltextruler.h"
#include "soiltextwidget.h"
#include "soiluielm.h"
#include "soilwidget.h"

#endif // SOILFRAMEWORK_H

